version: '3.2'
services:
  ied_1:
    build: docker/iec61850_base
    networks:
      - iec61850_network
    tty: true
    mac_address: 02:42:ac:12:00:01
    volumes:
      - "./goose:/goose"

  ied_2:
    build: docker/iec61850_base
    networks:
      - iec61850_network
    tty: true
    mac_address: 02:42:ac:12:00:02
    volumes:
      - "./goose:/goose"

  ied_3:
    build: docker/iec61850_base
    networks:
      - iec61850_network
    tty: true
    mac_address: 02:42:ac:12:00:03
    volumes:
      - "./goose:/goose"

  ied_4:
    build: docker/iec61850_base
    networks:
      - iec61850_network
    tty: true
    mac_address: 02:42:ac:12:00:04
    volumes:
      - "./goose:/goose"

networks:
  iec61850_network:
